// @generated by `mix osa.gen.tui_types` from
// OptimalSystemAgent.Protocol.TUISchema — DO NOT EDIT BY HAND.
//
// The Elixir protocol is the single source of truth for these payload shapes.
// Regenerate:        mix osa.gen.tui_types
// Verify up-to-date: mix osa.gen.tui_types --check
//
// types.rs re-exports everything here, so these payloads cannot drift from
// the Elixir HTTP API. Backend contract fields exist because the JSON schema
// requires them, not because Rust reads every one — dead_code is expected.
#![allow(dead_code)]

use serde::{Deserialize, Serialize};


// === Health — GET /health ===

#[derive(Debug, Clone, Deserialize)]
pub struct HealthResponse {
    pub status: String,
    pub version: String,
    #[serde(default)]
    pub uptime_seconds: i64,
    pub provider: String,
    pub model: String,
    #[serde(default)]
    pub context_window: Option<u64>,
    /// Current reasoning effort: "low" | "medium" | "high" | "max".
    /// `Option` + `default` keep older backends (which omit it) decodable.
    #[serde(default)]
    pub effort: Option<String>,
    /// Spend/limit snapshot from the backend Budget. `null` when Budget is
    /// unavailable; individual limits are `null` when uncapped.
    #[serde(default)]
    pub billing: Option<HealthBilling>,
}

/// Billing projection carried on `GET /health` (see tui-statusline-spec).
#[derive(Debug, Clone, Deserialize)]
pub struct HealthBilling {
    #[serde(default)]
    pub daily_spent_usd: f64,
    #[serde(default)]
    pub daily_limit_usd: Option<f64>,
    #[serde(default)]
    pub monthly_spent_usd: f64,
    #[serde(default)]
    pub monthly_limit_usd: Option<f64>,
    #[serde(default)]
    pub currency: String,
    /// Subscription/plan tier. Always `null` today (OSA has no plan concept),
    /// but wired so a chip appears if a plan is ever set.
    #[serde(default)]
    pub subscription: Option<String>,
    /// Tokens consumed today. Used to render a token-usage chip for providers
    /// that don't price in USD (e.g. glm), where a dollar figure is meaningless.
    #[serde(default)]
    pub daily_tokens: u64,
    /// Whether this provider's spend is denominated in USD. When false, the
    /// status line must never show a `$` figure — show token usage instead.
    #[serde(default)]
    pub usd_pricing: bool,
}

// === Orchestrate — POST /api/v1/orchestrate ===

#[derive(Debug, Clone, Serialize)]
pub struct OrchestrateRequest {
    pub input: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub skip_plan: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub working_dir: Option<String>,
    /// Attachments for vision-capable models: file paths or base64-encoded images.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<String>>,
}

/// 202 Accepted — the full reply arrives over the SSE stream.
#[derive(Debug, Clone, Deserialize)]
pub struct OrchestrateResponse {
    pub session_id: String,
    pub status: String,
}

// === Sessions ===

#[derive(Debug, Clone, Deserialize)]
pub struct SessionMessage {
    pub role: String,
    pub content: String,
    #[serde(default)]
    pub timestamp: Option<String>,
}

/// A session summary or a full session (with messages) from GET /sessions/:id.
#[derive(Debug, Clone, Deserialize)]
pub struct SessionInfo {
    pub id: String,
    pub created_at: String,
    #[serde(default)]
    pub title: String,
    #[serde(default)]
    pub message_count: i32,
    #[serde(default)]
    pub messages: Option<Vec<SessionMessage>>,
    /// Timestamp of the most recent turn (present on listings).
    #[serde(default)]
    pub last_active: Option<String>,
}

/// GET /api/v1/sessions — paginated session listing.
#[derive(Debug, Clone, Deserialize)]
pub struct SessionListResponse {
    pub sessions: Vec<SessionInfo>,
    #[serde(default)]
    pub count: i32,
    #[serde(default)]
    pub page: i32,
    #[serde(default)]
    pub per_page: i32,
}

/// POST /api/v1/sessions — created or resumed session.
#[derive(Debug, Clone, Deserialize)]
pub struct SessionCreateResponse {
    pub id: String,
    /// "created" for a new session, "resumed" when the folder already had one.
    #[serde(default)]
    pub status: Option<String>,
    #[serde(default)]
    pub working_dir: Option<String>,
    #[serde(default)]
    pub created_at: Option<String>,
    #[serde(default)]
    pub title: Option<String>,
}

/// GET /api/v1/sessions/:id/messages.
#[derive(Debug, Clone, Deserialize)]
pub struct SessionMessagesResponse {
    pub messages: Vec<SessionMessage>,
    #[serde(default)]
    pub count: i32,
}

/// GET /api/v1/sessions/:id/context — token-usage breakdown.
#[derive(Debug, Clone, Deserialize)]
pub struct ContextStats {
    #[serde(default)]
    pub system_tokens: u64,
    #[serde(default)]
    pub conversation_tokens: u64,
    #[serde(default)]
    pub tool_result_tokens: u64,
    #[serde(default)]
    pub max_tokens: u64,
    #[serde(default)]
    pub used_tokens: u64,
}

/// POST /api/v1/sessions/:id/compact — proactive compaction result.
#[derive(Debug, Clone, Deserialize)]
pub struct CompactResponse {
    #[serde(default)]
    pub status: String,
    #[serde(default)]
    pub messages_before: u64,
    #[serde(default)]
    pub messages_after: u64,
    #[serde(default)]
    pub tokens_before: u64,
    #[serde(default)]
    pub tokens_after: u64,
}

/// GET /api/v1/sessions/:id/recap — short LLM summary of the session.
#[derive(Debug, Clone, Deserialize)]
pub struct RecapResponse {
    #[serde(default)]
    pub session_id: String,
    #[serde(default)]
    pub recap: String,
}

// === Runs — GET /runs ===

/// A single agent run projected from RunStore.
#[derive(Debug, Clone, Deserialize)]
pub struct RunSummary {
    pub id: String,
    #[serde(default)]
    pub role: Option<String>,
    pub status: String,
    #[serde(default)]
    pub parent_session_id: Option<String>,
    #[serde(default)]
    pub started_at: Option<String>,
    #[serde(default)]
    pub completed_at: Option<String>,
    #[serde(default)]
    pub duration_ms: Option<i64>,
    #[serde(default)]
    pub tokens: i64,
    #[serde(default)]
    pub tool_count: i32,
    #[serde(default)]
    pub task_preview: String,
}

/// GET /runs — active + background runs, newest first.
#[derive(Debug, Clone, Deserialize)]
pub struct RunListResponse {
    pub runs: Vec<RunSummary>,
    #[serde(default)]
    pub active: Vec<RunSummary>,
    #[serde(default)]
    pub active_count: i32,
    #[serde(default)]
    pub count: i32,
}

/// POST /runs/:id/cancel.
#[derive(Debug, Clone, Deserialize)]
pub struct RunCancelResponse {
    pub status: String,
    pub run_id: String,
}

// === Rewind — /rewind ===

/// A snapshot of conversation (and optionally code) taken before a user prompt.
#[derive(Debug, Clone, Deserialize)]
pub struct RewindCheckpoint {
    pub id: String,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub created_at: Option<String>,
    #[serde(default)]
    pub iteration: i64,
    #[serde(default)]
    pub message_count: i64,
    #[serde(default)]
    pub has_code: bool,
}

/// GET /api/v1/rewind/:session_id — recent checkpoints, newest first.
#[derive(Debug, Clone, Deserialize)]
pub struct RewindListResponse {
    pub checkpoints: Vec<RewindCheckpoint>,
    #[serde(default)]
    pub count: i32,
}

/// POST /api/v1/rewind/restore. scope in "code" | "conversation" | "both".
#[derive(Debug, Clone, Serialize)]
pub struct RewindRestoreRequest {
    pub session_id: String,
    pub checkpoint_id: String,
    pub scope: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RewindRestoreResponse {
    #[serde(default)]
    pub scope: String,
    #[serde(default)]
    pub message_count: Option<i64>,
}

// === Errors — shared error envelope (incl. /config not_implemented) ===

#[derive(Debug, Clone, Deserialize)]
pub struct ErrorResponse {
    pub error: String,
    #[serde(default)]
    pub code: Option<String>,
    #[serde(default)]
    pub details: Option<String>,
}
