defmodule OptimalSystemAgent.OnboardingAuthModesTest do
  @moduledoc """
  Stage 1 regression lock for the dual-mode provider auth refactor.

  The refactor generalised a hardcoded per-provider auth fork into an
  `auth_modes` field on `Onboarding.providers_list/0`. The entire value of
  doing it that way rests on one claim: **every provider that only takes an
  API key behaves exactly as it did before the field existed.** These tests
  exist to make that claim falsifiable rather than assumed.

  The strongest assertion here is `providers_list/0` compared against
  `test/support/fixtures/providers_list_baseline.exs`, which was generated by
  compiling the pre-refactor `onboarding.ex` (from the commit before this
  work) and dumping its output. If a future change perturbs any existing
  provider entry — a renamed key, a reordered list, a changed default — this
  test fails with a diff, which is precisely the regression the refactor
  promised could not happen.
  """

  use ExUnit.Case, async: true

  alias OptimalSystemAgent.Onboarding

  @baseline_path "test/support/fixtures/providers_list_baseline.exs"

  # Stage 1 adds NO catalog entries: a provider entry lands together with the
  # Registry routing that makes it usable, never before it (the BYOK suite
  # enforces exactly that — "a provider you can select but never use is worse
  # than one that is absent"). So the whole catalog must be untouched here.
  # Providers added BY this feature. Each lands together with the Registry
  # routing that makes it usable — never before it (the BYOK suite enforces
  # exactly that: "a provider you can select but never use is worse than one
  # that is absent"). Everything NOT listed here must be untouched.
  @new_provider_ids ["openai_codex"]

  defp baseline do
    {list, _} = Code.eval_file(@baseline_path)
    list
  end

  defp preexisting do
    Enum.reject(Onboarding.providers_list(), &(&1.id in @new_provider_ids))
  end

  # A synthetic dual-mode provider. Stage 1 is the machinery, not a
  # provider, so the fork is exercised against the pure decision functions
  # with an entry supplied directly — rather than by parking a half-wired
  # entry in the real catalog just to have something to point at.
  defp dual_mode_entry do
    %{
      # `copilot` is used as the id because an Auth.Subscription
      # implementation IS registered for it — only its CATALOG entry is
      # deferred until the provider routing lands. So this exercises the
      # real availability check rather than stubbing it.
      id: "copilot",
      name: "Example",
      auth_modes: [:api_key, :oauth],
      subscription: %{
        kind: :device_code,
        label: "Sign in with Example",
        hint: "Uses your Example plan — no per-token billing",
        key_label: "Paste an API key",
        key_hint: "Pay-per-token billing"
      }
    }
  end

  describe "the 27 pre-existing providers are unaffected" do
    test "stripping :auth_modes reproduces the pre-refactor provider list exactly" do
      # `:auth_modes` is the ONLY field the refactor added to existing entries.
      # Remove it and what remains must be byte-identical to what the previous
      # implementation produced — same entries, same order, same values.
      stripped = Enum.map(preexisting(), &Map.delete(&1, :auth_modes))

      assert stripped == baseline()
    end

    test "there are still exactly 27 of them, with the same ids in the same order" do
      assert length(preexisting()) == 27
      assert Enum.map(preexisting(), & &1.id) == Enum.map(baseline(), & &1.id)
    end

    test "every one of them declares key-only auth" do
      for p <- preexisting() do
        assert p.auth_modes == [:api_key],
               "#{p.id} unexpectedly declares #{inspect(p.auth_modes)}; " <>
                 "adding a mode here changes its setup flow"
      end
    end

    test "none of them renders an auth fork" do
      # `auth_options/1` returning [] is what makes the CLI take the identical
      # branch it took before: straight to the key prompt, no extra question,
      # no extra keystroke.
      for p <- preexisting() do
        assert Onboarding.auth_options(p.id) == [],
               "#{p.id} would now show an auth-method menu it did not show before"
      end
    end

    test "none of them can be routed into a sign-in flow, even if one is requested" do
      # Defence in depth: a stale TUI client, a scripted run or a bug passing
      # `:oauth` for a key-only provider must resolve to the key path rather
      # than dispatching into a sign-in implementation that does not exist.
      for p <- preexisting() do
        assert Onboarding.auth_route(p.id, :oauth) == :api_key
        assert Onboarding.auth_route(p.id, nil) == :api_key
        assert Onboarding.auth_route(p.id, :api_key) == :api_key
      end
    end

    test "auth_modes/1 defaults unknown ids to key-only rather than raising" do
      assert Onboarding.auth_modes("no-such-provider") == [:api_key]
      assert Onboarding.auth_options("no-such-provider") == []
      assert Onboarding.auth_route("no-such-provider", :oauth) == :api_key
      refute Onboarding.dual_mode?("no-such-provider")
    end
  end

  describe "a provider declaring [:api_key, :oauth]" do
    setup do
      # Sign-in is only OFFERED when the build can actually perform it, so the
      # fork tests need a configured client id.
      prev = Application.get_env(:optimal_system_agent, :copilot_client_id)
      Application.put_env(:optimal_system_agent, :copilot_client_id, "Iv1.test-client-id")
      on_exit(fn -> restore(:copilot_client_id, prev) end)
      :ok
    end

    test "offers both ways in, sign-in first, described by billing model" do
      assert [oauth, api_key] = Onboarding.auth_options_for(dual_mode_entry())

      assert oauth.value == :oauth
      assert api_key.value == :api_key

      # The hint must name what the user is choosing between — which account
      # pays — not the protocol, which they do not care about.
      assert oauth.hint =~ ~r/subscription|plan/i
      assert oauth.label =~ "Sign in"
      assert api_key.label =~ ~r/token|key/i
      assert api_key.hint =~ ~r/pay-per-token/i
    end

    test "either choice is honoured, and both are legitimate routes" do
      modes = Onboarding.usable_auth_modes_for(dual_mode_entry())

      assert :oauth in modes
      assert :api_key in modes
      assert Onboarding.auth_route_for(modes, :oauth) == :oauth
      assert Onboarding.auth_route_for(modes, :api_key) == :api_key

      # The default with no explicit choice is the mode that works everywhere
      # and never blocks on a browser.
      assert Onboarding.auth_route_for(modes, nil) == :api_key
    end

    test "falls back to generic labels when the entry declares no subscription copy" do
      bare = %{id: "copilot", name: "Example", auth_modes: [:api_key, :oauth]}

      assert [oauth, api_key] = Onboarding.auth_options_for(bare)
      assert oauth.label == "Sign in with Example"
      assert api_key.label == "Paste an API key"
    end
  end

  describe "when sign-in is not available in this build" do
    setup do
      prev = Application.get_env(:optimal_system_agent, :copilot_client_id)
      Application.delete_env(:optimal_system_agent, :copilot_client_id)
      prev_env = System.get_env("OSA_COPILOT_CLIENT_ID")
      System.delete_env("OSA_COPILOT_CLIENT_ID")

      on_exit(fn ->
        restore(:copilot_client_id, prev)
        if prev_env, do: System.put_env("OSA_COPILOT_CLIENT_ID", prev_env)
      end)

      :ok
    end

    test "the provider degrades to a plain key prompt instead of offering a dead end" do
      entry = dual_mode_entry()

      # It still DECLARES :oauth — the capability is real...
      assert :oauth in Map.fetch!(entry, :auth_modes)

      # ...but it cannot be performed without a registered client id, so it is
      # not offered, and the provider behaves exactly like the other 27.
      modes = Onboarding.usable_auth_modes_for(entry)
      refute :oauth in modes
      assert Onboarding.auth_options_for(entry) == []
      assert Onboarding.auth_route_for(modes, :oauth) == :api_key
    end
  end

  describe "serialization to the TUI / desktop onboarding" do
    test "auth_modes survives JSON encoding so all three surfaces read one source" do
      # GET /onboarding/status serializes providers_list/0 verbatim, so the
      # field must round-trip rather than being a CLI-only concept — that is
      # what stops the surfaces from growing separate, disagreeing lists.
      encoded = Jason.encode!(Onboarding.providers_list())
      decoded = Jason.decode!(encoded)

      for entry <- decoded do
        assert is_list(entry["auth_modes"])
        assert entry["auth_modes"] != []
      end

      # Today every catalog entry is key-only, so the serialized value is the
      # default. The point of asserting it is that the FIELD reaches the TUI at
      # all: when a dual-mode provider lands, its extra option appears in the
      # desktop/TUI picker without a second, separately-maintained list.
      codex = Enum.find(decoded, &(&1["id"] == "openai_codex"))
      assert codex["auth_modes"] == ["oauth"], "the TUI must learn about sign-in from this field alone"

      for entry <- decoded, entry["id"] not in ["openai_codex"] do
        assert entry["auth_modes"] == ["api_key"]
      end
    end
  end

  defp restore(key, nil), do: Application.delete_env(:optimal_system_agent, key)
  defp restore(key, value), do: Application.put_env(:optimal_system_agent, key, value)
end
