defmodule OptimalSystemAgent.OnboardingAuthModesTest do
  @moduledoc """
  Stage 1 regression lock for the dual-mode provider auth refactor.

  The refactor generalised a hardcoded per-provider auth fork into an
  `auth_modes` field on `Onboarding.providers_list/0`. The entire value of
  doing it that way rests on one claim: **every provider that only takes an
  API key behaves exactly as it did before the field existed.** These tests
  exist to make that claim falsifiable rather than assumed.

  The strongest assertion here is `providers_list/0` compared against
  `test/support/fixtures/providers_list_baseline.exs`, which was generated by
  compiling the pre-refactor `onboarding.ex` (from the commit before this
  work) and dumping its output. If a future change perturbs any existing
  provider entry — a renamed key, a reordered list, a changed default — this
  test fails with a diff, which is precisely the regression the refactor
  promised could not happen.
  """

  use ExUnit.Case, async: true

  alias OptimalSystemAgent.Onboarding

  @baseline_path "test/support/fixtures/providers_list_baseline.exs"

  # Stage 1 adds NO catalog entries: a provider entry lands together with the
  # Registry routing that makes it usable, never before it (the BYOK suite
  # enforces exactly that — "a provider you can select but never use is worse
  # than one that is absent"). So the whole catalog must be untouched here.
  # Providers added BY this feature. Each lands together with the Registry
  # routing that makes it usable — never before it (the BYOK suite enforces
  # exactly that: "a provider you can select but never use is worse than one
  # that is absent"). Everything NOT listed here must be untouched.
  @new_provider_ids ["openai_codex", "claude_cli", "copilot_cli", "bedrock"]

  # Pre-existing providers that have since GAINED a second auth mode in place,
  # rather than being split into a second entry. The test for which pattern
  # applies is whether anything besides the CREDENTIAL differs:
  #
  #   * `ollama_cloud` — account mode is a signed-in local daemon, key mode is
  #     ollama.com. Same models either way.
  #   * `xai` — same host (`api.x.ai/v1`), same OpenAI-compatible wire format,
  #     same models. Only the credential differs.
  #   * `qwen` — same OpenAI-compatible wire format and the same live-resolved
  #     models. The endpoint does differ, but only because the provider issues
  #     an account its own `resource_url` while a DashScope key belongs to
  #     DashScope — the `ollama_cloud` situation exactly.
  #
  # Contrast the `openai`/`openai_codex` split, which is two entries precisely
  # because the base URL, the protocol AND the model list all change with the
  # credential.
  #
  # These are still held to the baseline — everything about the entry except
  # the fields the fork adds must be unchanged, which is what says the key
  # path still works exactly as it did. What they are exempt from is the
  # "declares key-only auth" assertion, which is the thing that deliberately
  # changed.
  #
  # Adding an id here is the deliberate, written-down decision that a provider
  # gained a second mode. A catalog edit alone cannot do it.
  @dual_mode_ids ["ollama_cloud", "qwen", "xai"]

  # The fields a dual-mode upgrade is allowed to add to an existing entry.
  #
  # `:key_optional` is one of them, and it belongs here rather than being
  # treated as an unexplained catalog change: it is what makes BOTH modes
  # reachable from the TUI, whose onboarding dialog decides whether to render
  # a credential field from `requires_key` alone. Without it the key would be
  # mandatory and the account mode unreachable there; with `requires_key:
  # false` instead, the KEY mode would be unreachable. The pairing is the
  # fork, so it is scoped to dual-mode ids like the other two.
  #
  # Because these are stripped from BOTH sides of the baseline comparison, the
  # "still offers its key" test below asserts the affordance directly — the
  # claim is checked somewhere, just not by a diff that would also fire on a
  # legitimate upgrade.
  @fork_fields [:auth_modes, :subscription, :key_optional]

  # Presentation-only fields every entry now carries: which tab a setup surface
  # files it under, and its position within that tab.
  #
  # Stripped alongside `:auth_modes` for the same reason and with the same
  # force: this test's claim is that the pre-existing providers are
  # BEHAVIOURALLY unchanged, and grouping metadata changes where a row is
  # drawn, not what happens when it is chosen. Both are derived — `tab` from
  # `auth_modes`, `order` from catalog position — so neither can encode a
  # decision the rest of the entry does not already make.
  #
  # They are listed explicitly rather than the assertion being loosened to a
  # subset match, so the next field added to the catalog still fails this test
  # and has to argue for itself here.
  @grouping_fields [:tab, :order]

  defp baseline do
    {list, _} = Code.eval_file(@baseline_path)
    list
  end

  defp preexisting do
    Enum.reject(Onboarding.providers_list(), &(&1.id in @new_provider_ids))
  end

  defp key_only do
    Enum.reject(preexisting(), &(&1.id in @dual_mode_ids))
  end

  # A synthetic dual-mode provider. Stage 1 is the machinery, not a
  # provider, so the fork is exercised against the pure decision functions
  # with an entry supplied directly — rather than by parking a half-wired
  # entry in the real catalog just to have something to point at.
  defp dual_mode_entry do
    %{
      # `copilot` is used as the id because an Auth.Subscription
      # implementation IS registered for it — only its CATALOG entry is
      # deferred until the provider routing lands. So this exercises the
      # real availability check rather than stubbing it.
      id: "copilot",
      name: "Example",
      auth_modes: [:api_key, :oauth],
      subscription: %{
        kind: :device_code,
        label: "Sign in with Example",
        hint: "Uses your Example plan — no per-token billing",
        key_label: "Paste an API key",
        key_hint: "Pay-per-token billing"
      }
    }
  end

  describe "the 27 pre-existing providers are unaffected" do
    test "stripping :auth_modes reproduces the pre-refactor provider list exactly" do
      # `:auth_modes` is the ONLY field the refactor added to existing entries.
      # Remove it and what remains must be byte-identical to what the previous
      # implementation produced — same entries, same order, same values.
      # `:subscription` is stripped too, for the one entry that gained a second
      # mode in place. Everything else about that entry — env var, base URL,
      # key affordance, model catalog — must still match, which is exactly the
      # claim "the API-key path is unchanged" rests on.
      # Stripped from BOTH sides for the dual-mode ids, so the comparison is
      # symmetric: a fork field is exempt whether the baseline happened to
      # carry it already (`ollama_cloud` did) or the upgrade added it (`xai`
      # and `qwen` did). Every OTHER field — env var, base URL, signup URL,
      # default model, model catalog, name, description, group — is still
      # compared exactly, and that is the claim "the API-key path is
      # unchanged" actually rests on.
      strip = fn p ->
        drop =
          if(p.id in @dual_mode_ids, do: @fork_fields, else: [:auth_modes]) ++ @grouping_fields

        Map.drop(p, drop)
      end

      assert Enum.map(preexisting(), strip) == Enum.map(baseline(), strip)
    end

    test "there are still exactly 27 of them, with the same ids in the same order" do
      assert length(preexisting()) == 27
      assert Enum.map(preexisting(), & &1.id) == Enum.map(baseline(), & &1.id)
    end

    test "every one of them declares key-only auth" do
      for p <- key_only() do
        assert p.auth_modes == [:api_key],
               "#{p.id} unexpectedly declares #{inspect(p.auth_modes)}; " <>
                 "adding a mode here changes its setup flow"
      end
    end

    test "the one dual-mode upgrade is deliberate and still offers its key" do
      # Held explicitly so that gaining a second mode is a decision somebody
      # wrote down, not something a catalog edit can do by accident.
      for id <- @dual_mode_ids do
        entry = Enum.find(preexisting(), &(&1.id == id))
        assert entry.auth_modes == [:api_key, :oauth]
        assert :api_key in Onboarding.usable_auth_modes(id)
        assert Onboarding.auth_route(id, :api_key) == :api_key
        assert Onboarding.auth_route(id, nil) == :api_key

        # The affordance the baseline diff can no longer see, asserted here
        # instead: a dual-mode row must still RENDER a credential field (so
        # the key mode stays reachable from the TUI) and must not REQUIRE one
        # (so the account mode is reachable at all).
        assert entry.requires_key == true, "#{id} must still render a key field"
        assert entry.key_optional == true, "#{id} must not force a key"

        # And the sign-in half is real, not merely declared.
        assert :oauth in Onboarding.usable_auth_modes(id),
               "#{id} declares :oauth but cannot perform it"

        assert Onboarding.auth_route(id, :oauth) == :oauth
        assert Map.has_key?(entry, :subscription)
      end
    end

    test "none of them renders an auth fork" do
      # `auth_options/1` returning [] is what makes the CLI take the identical
      # branch it took before: straight to the key prompt, no extra question,
      # no extra keystroke.
      for p <- key_only() do
        assert Onboarding.auth_options(p.id) == [],
               "#{p.id} would now show an auth-method menu it did not show before"
      end
    end

    test "none of them can be routed into a sign-in flow, even if one is requested" do
      # Defence in depth: a stale TUI client, a scripted run or a bug passing
      # `:oauth` for a key-only provider must resolve to the key path rather
      # than dispatching into a sign-in implementation that does not exist.
      for p <- key_only() do
        assert Onboarding.auth_route(p.id, :oauth) == :api_key
        assert Onboarding.auth_route(p.id, nil) == :api_key
        assert Onboarding.auth_route(p.id, :api_key) == :api_key
      end
    end

    test "auth_modes/1 defaults unknown ids to key-only rather than raising" do
      assert Onboarding.auth_modes("no-such-provider") == [:api_key]
      assert Onboarding.auth_options("no-such-provider") == []
      assert Onboarding.auth_route("no-such-provider", :oauth) == :api_key
      refute Onboarding.dual_mode?("no-such-provider")
    end
  end

  describe "a provider declaring [:api_key, :oauth]" do
    setup do
      # Sign-in is only OFFERED when the build can actually perform it, so the
      # fork tests need a configured client id.
      prev = Application.get_env(:optimal_system_agent, :copilot_client_id)
      Application.put_env(:optimal_system_agent, :copilot_client_id, "Iv1.test-client-id")
      on_exit(fn -> restore(:copilot_client_id, prev) end)
      :ok
    end

    test "offers both ways in, sign-in first, described by billing model" do
      assert [oauth, api_key] = Onboarding.auth_options_for(dual_mode_entry())

      assert oauth.value == :oauth
      assert api_key.value == :api_key

      # The hint must name what the user is choosing between — which account
      # pays — not the protocol, which they do not care about.
      assert oauth.hint =~ ~r/subscription|plan/i
      assert oauth.label =~ "Sign in"
      assert api_key.label =~ ~r/token|key/i
      assert api_key.hint =~ ~r/pay-per-token/i
    end

    test "either choice is honoured, and both are legitimate routes" do
      modes = Onboarding.usable_auth_modes_for(dual_mode_entry())

      assert :oauth in modes
      assert :api_key in modes
      assert Onboarding.auth_route_for(modes, :oauth) == :oauth
      assert Onboarding.auth_route_for(modes, :api_key) == :api_key

      # The default with no explicit choice is the mode that works everywhere
      # and never blocks on a browser.
      assert Onboarding.auth_route_for(modes, nil) == :api_key
    end

    test "falls back to generic labels when the entry declares no subscription copy" do
      bare = %{id: "copilot", name: "Example", auth_modes: [:api_key, :oauth]}

      assert [oauth, api_key] = Onboarding.auth_options_for(bare)
      assert oauth.label == "Sign in with Example"
      assert api_key.label == "Paste an API key"
    end
  end

  describe "when sign-in is not available in this build" do
    setup do
      prev = Application.get_env(:optimal_system_agent, :copilot_client_id)
      Application.delete_env(:optimal_system_agent, :copilot_client_id)
      prev_env = System.get_env("OSA_COPILOT_CLIENT_ID")
      System.delete_env("OSA_COPILOT_CLIENT_ID")

      on_exit(fn ->
        restore(:copilot_client_id, prev)
        if prev_env, do: System.put_env("OSA_COPILOT_CLIENT_ID", prev_env)
      end)

      :ok
    end

    test "the provider degrades to a plain key prompt instead of offering a dead end" do
      entry = dual_mode_entry()

      # It still DECLARES :oauth — the capability is real...
      assert :oauth in Map.fetch!(entry, :auth_modes)

      # ...but it cannot be performed without a registered client id, so it is
      # not offered, and the provider behaves exactly like the other 27.
      modes = Onboarding.usable_auth_modes_for(entry)
      refute :oauth in modes
      assert Onboarding.auth_options_for(entry) == []
      assert Onboarding.auth_route_for(modes, :oauth) == :api_key
    end
  end

  describe "serialization to the TUI / desktop onboarding" do
    test "auth_modes survives JSON encoding so all three surfaces read one source" do
      # GET /onboarding/status serializes providers_list/0 verbatim, so the
      # field must round-trip rather than being a CLI-only concept — that is
      # what stops the surfaces from growing separate, disagreeing lists.
      encoded = Jason.encode!(Onboarding.providers_list())
      decoded = Jason.decode!(encoded)

      for entry <- decoded do
        assert is_list(entry["auth_modes"])
        assert entry["auth_modes"] != []
      end

      # Today every catalog entry is key-only, so the serialized value is the
      # default. The point of asserting it is that the FIELD reaches the TUI at
      # all: when a dual-mode provider lands, its extra option appears in the
      # desktop/TUI picker without a second, separately-maintained list.
      codex = Enum.find(decoded, &(&1["id"] == "openai_codex"))

      assert codex["auth_modes"] == ["oauth"],
             "the TUI must learn about sign-in from this field alone"

      claude = Enum.find(decoded, &(&1["id"] == "claude_cli"))

      assert claude["auth_modes"] == ["oauth"],
             "the Claude Code bridge must reach the TUI through the same field, not a second list"

      copilot = Enum.find(decoded, &(&1["id"] == "copilot_cli"))
      assert copilot["auth_modes"] == ["oauth"]

      # The dual-mode upgrade reaches the TUI through the same field — both
      # options, in the catalog's canonical order.
      ollama = Enum.find(decoded, &(&1["id"] == "ollama_cloud"))
      assert ollama["auth_modes"] == ["api_key", "oauth"]
      assert ollama["subscription"]["kind"] == "local_daemon"

      # The compact `@additional_providers` rows reach the TUI through the
      # same field. These two are built from a tuple and decorated by an
      # overlay, so this is also the check that the overlay's output survives
      # serialization rather than being a CLI-only shape.
      for id <- ["xai", "qwen"] do
        row = Enum.find(decoded, &(&1["id"] == id))

        assert row["auth_modes"] == ["api_key", "oauth"], "#{id} must reach the TUI dual-mode"
        assert row["subscription"]["kind"] == "device_code"
        assert row["key_optional"] == true
        assert row["requires_key"] == true
      end

      for entry <- decoded, entry["id"] not in (@new_provider_ids ++ @dual_mode_ids) do
        assert entry["auth_modes"] == ["api_key"]
      end
    end
  end

  defp restore(key, nil), do: Application.delete_env(:optimal_system_agent, key)
  defp restore(key, value), do: Application.put_env(:optimal_system_agent, key, value)
end
