defmodule OptimalSystemAgent.Protocol.TUISchemaTest do
  use ExUnit.Case, async: true

  alias OptimalSystemAgent.Protocol.TUISchema

  describe "protocol declaration" do
    test "every type has a name, a valid derive, and fields" do
      for type <- TUISchema.types() do
        assert is_binary(type.name) and type.name != ""
        assert type.derive in [:serialize, :deserialize]
        assert is_list(type.fields) and type.fields != []

        for field <- type.fields do
          assert is_binary(field.name) and field.name != ""
        end
      end
    end

    test "type names are unique" do
      names = TUISchema.type_names()
      assert names == Enum.uniq(names)
    end

    test "covers the core payloads from issue #33" do
      names = MapSet.new(TUISchema.type_names())

      for expected <- [
            "HealthResponse",
            "OrchestrateRequest",
            "OrchestrateResponse",
            "SessionInfo",
            "SessionMessage",
            "SessionCreateResponse",
            "ContextStats",
            "RunSummary",
            "RunListResponse",
            "RewindCheckpoint",
            "RewindRestoreRequest",
            "RewindRestoreResponse",
            "ErrorResponse"
          ] do
        assert MapSet.member?(names, expected), "protocol is missing #{expected}"
      end
    end

    test "every struct reference points at a declared type" do
      declared = MapSet.new(TUISchema.type_names())

      refs =
        for type <- TUISchema.types(), field <- type.fields, uniq: true do
          struct_ref(field.type)
        end
        |> Enum.reject(&is_nil/1)

      for ref <- refs do
        assert MapSet.member?(declared, ref), "reference to undeclared struct #{ref}"
      end
    end
  end

  describe "Rust rendering" do
    test "renders the @generated banner and serde derives" do
      rust = TUISchema.render()

      assert rust =~ "@generated by `mix osa.gen.tui_types`"
      assert rust =~ "#![allow(dead_code)]"
      assert rust =~ "use serde::{Deserialize, Serialize};"
    end

    test "maps Elixir types onto the expected Rust shapes" do
      rust = TUISchema.render()

      # Option<u64> with serde default
      assert rust =~ "#[serde(default)]\n    pub context_window: Option<u64>,"
      # request optionals use skip_serializing_if
      assert rust =~
               ~s|#[serde(skip_serializing_if = "Option::is_none")]\n    pub session_id: Option<String>,|
      # nested Vec<Struct>
      assert rust =~ "pub messages: Option<Vec<SessionMessage>>,"
      assert rust =~ "pub runs: Vec<RunSummary>,"
      # request structs derive Serialize, responses Deserialize
      assert rust =~ "#[derive(Debug, Clone, Serialize)]\npub struct OrchestrateRequest"
      assert rust =~ "#[derive(Debug, Clone, Deserialize)]\npub struct HealthResponse"
    end
  end

  describe "generated.rs is up to date (drift guard)" do
    test "the committed generated.rs matches the current schema" do
      path = TUISchema.output_path()

      assert File.exists?(path),
             "#{TUISchema.relative_output_path()} is missing — run `mix osa.gen.tui_types`"

      assert TUISchema.up_to_date?(),
             """
             #{TUISchema.relative_output_path()} is OUT OF DATE relative to \
             OptimalSystemAgent.Protocol.TUISchema.
             Run `mix osa.gen.tui_types` and commit the result.
             """
    end
  end

  # Extract the referenced struct name from a field type, if any.
  defp struct_ref({:struct, name}), do: name
  defp struct_ref({:option, t}), do: struct_ref(t)
  defp struct_ref({:vec, t}), do: struct_ref(t)
  defp struct_ref({:map, _k, v}), do: struct_ref(v)
  defp struct_ref(_), do: nil
end
