defmodule OptimalSystemAgent.Security.CodeFixPr do
  @moduledoc """
  Open a GitHub PR from stored AutoFix diffs.

  `CodeFix` records `fix_before`/`fix_after` pairs. This module applies those
  replacements on disk, then drives `git` + `gh pr create` through an injected
  `:runner` so tests never shell out to a live GitHub API.

  Command sequence:

    1. `git checkout -b <branch>`
    2. apply patches with `File.read`/`File.write` in `:cwd` (not `patch(1)`)
    3. `git add <files>`
    4. `git commit -m <title>`
    5. `git push -u origin <branch>`
    6. `gh pr create --base <base> --title <title> --body <body>`
  """

  require Logger

  alias OptimalSystemAgent.Security.CodeFix

  @default_base "main"
  @default_title "fix(security): apply OSA autofix"
  @review_line "Generated by OSA AutoFix. Review before merge."

  @type result :: %{
          url: String.t() | nil,
          branch: String.t(),
          applied: [String.t()],
          skipped: [String.t()],
          sha: String.t() | nil
        }

  @doc """
  Apply stored (or passed) fixes and open a PR.

  Required: `:cwd` (git repo path). `:fixes` is required when `CodeFix.list/1`
  cannot be called or returns empty. Inject `:runner` in tests.
  """
  @spec open_pr(String.t(), keyword()) :: {:ok, result()} | {:error, String.t()}
  def open_pr(session_id, opts \\ []) when is_binary(session_id) and is_list(opts) do
    with {:ok, cwd} <- require_cwd(opts),
         {:ok, fixes} <- load_fixes(session_id, opts) do
      apply_and_open(session_id, fixes, cwd, opts)
    end
  end

  @doc """
  Markdown PR body: finding key, file path, explanation, unified-diff
  before/after, plus the review line. `extra` is appended when non-empty.
  """
  @spec render_body([map()], String.t()) :: String.t()
  def render_body(fixes, extra) when is_list(fixes) and is_binary(extra) do
    blocks =
      Enum.map(fixes, fn fix ->
        key = field(fix, :finding_key) || "unknown"
        path = field(fix, :file_path) || "unknown"
        expl = field(fix, :explanation) || ""
        before = field(fix, :fix_before) || ""
        after_code = field(fix, :fix_after) || ""

        before_lines = diff_lines(before, "-")
        after_lines = diff_lines(after_code, "+")

        """
        ### `#{key}` (`#{path}`)

        #{expl}

        ```diff
        --- a/#{path}
        +++ b/#{path}
        #{before_lines}
        #{after_lines}
        ```
        """
      end)

    [@review_line <> "\n" | blocks]
    |> maybe_append_extra(extra)
    |> Enum.join("\n")
    |> String.trim()
    |> Kernel.<>("\n")
  end

  # ── Pipeline ───────────────────────────────────────────────────────────

  defp apply_and_open(session_id, fixes, cwd, opts) do
    runner = Keyword.get(opts, :runner) || (&default_run/2)
    apply? = Keyword.get(opts, :apply, true)
    branch = Keyword.get(opts, :branch) || default_branch(session_id)
    base = Keyword.get(opts, :base, @default_base)
    title = Keyword.get(opts, :title, @default_title)
    extra = Keyword.get(opts, :body, "") || ""
    run_opts = [cd: cwd]

    with {:ok, _} <- run(runner, ["git", "checkout", "-b", branch], run_opts) do
      %{applied: applied, skipped: skipped} = apply_fixes(fixes, cwd, apply?)

      if applied == [] do
        {:error, "no fixes applied"}
      else
        body = build_pr_body(fixes, extra, skipped)

        with {:ok, _} <- run(runner, ["git", "add" | applied], run_opts),
             {:ok, commit_out} <- run(runner, ["git", "commit", "-m", title], run_opts) do
          sha = resolve_sha(runner, run_opts, commit_out)

          with {:ok, _} <- run(runner, ["git", "push", "-u", "origin", branch], run_opts),
               {:ok, gh_out} <-
                 run(
                   runner,
                   ["gh", "pr", "create", "--base", base, "--title", title, "--body", body],
                   run_opts
                 ) do
            {:ok,
             %{
               url: parse_pr_url(gh_out),
               branch: branch,
               applied: applied,
               skipped: skipped,
               sha: sha
             }}
          end
        end
      end
    end
  end

  defp build_pr_body(fixes, extra, skipped) do
    extra_with_skipped =
      case skipped do
        [] -> extra
        paths -> join_extra(extra, skipped_section(paths))
      end

    render_body(fixes, extra_with_skipped)
  end

  defp skipped_section(paths) do
    "Skipped (not applied):\n" <> Enum.map_join(paths, "\n", &"- #{&1}")
  end

  defp join_extra("", rest), do: rest
  defp join_extra(extra, rest), do: extra <> "\n\n" <> rest

  # ── Apply ──────────────────────────────────────────────────────────────

  defp apply_fixes(fixes, cwd, apply?) do
    Enum.reduce(fixes, %{applied: [], skipped: []}, fn fix, acc ->
      path = field(fix, :file_path)
      before = field(fix, :fix_before)
      afterc = field(fix, :fix_after)

      case apply_one(cwd, path, before, afterc, apply?) do
        :ok ->
          %{acc | applied: acc.applied ++ [path]}

        {:skip, reason} ->
          Logger.warning("CodeFixPr skipped #{inspect(path)}: #{reason}")
          %{acc | skipped: acc.skipped ++ [path_or_unknown(path)]}
      end
    end)
  end

  defp path_or_unknown(path) when is_binary(path) and path != "", do: path
  defp path_or_unknown(_), do: "unknown"

  defp apply_one(_cwd, path, _before, _after, _apply?)
       when not is_binary(path) or path == "" do
    {:skip, "missing file_path"}
  end

  defp apply_one(_cwd, _path, before, _after, _apply?)
       when not is_binary(before) or before == "" do
    {:skip, "missing fix_before"}
  end

  defp apply_one(cwd, path, before, afterc, apply?) do
    case safe_path(cwd, path) do
      nil ->
        {:skip, "path escapes cwd"}

      abs ->
        replace_once(abs, before, afterc || "", apply?)
    end
  end

  defp replace_once(abs, before, afterc, apply?) do
    if File.regular?(abs) do
      content = File.read!(abs)

      case String.split(content, before, parts: 2) do
        [_only] ->
          {:skip, "fix_before not found"}

        [pre, post] ->
          if apply?, do: File.write!(abs, pre <> afterc <> post)
          :ok
      end
    else
      {:skip, "file missing"}
    end
  rescue
    e -> {:skip, Exception.message(e)}
  end

  defp safe_path(cwd, path) do
    cwd = Path.expand(cwd)
    abs = Path.expand(path, cwd)

    if abs == cwd or String.starts_with?(abs, cwd <> "/") do
      abs
    else
      nil
    end
  end

  # ── Fixes source ───────────────────────────────────────────────────────

  defp require_cwd(opts) do
    case Keyword.get(opts, :cwd) do
      cwd when is_binary(cwd) and cwd != "" ->
        if File.dir?(cwd) do
          {:ok, cwd}
        else
          {:error, "cwd not found: #{cwd}"}
        end

      _ ->
        {:error, "cwd is required"}
    end
  end

  defp load_fixes(session_id, opts) do
    case Keyword.fetch(opts, :fixes) do
      {:ok, []} ->
        {:error, "empty fixes"}

      {:ok, fixes} when is_list(fixes) ->
        {:ok, fixes}

      {:ok, _} ->
        {:error, "fixes must be a list"}

      :error ->
        fetch_stored_fixes(session_id)
    end
  end

  defp fetch_stored_fixes(session_id) do
    try do
      case CodeFix.list(session_id) do
        {:ok, [_ | _] = fixes} -> {:ok, fixes}
        {:ok, []} -> {:error, "no recorded fixes; pass :fixes"}
        {:error, reason} -> {:error, to_string(reason)}
      end
    rescue
      e ->
        {:error, "code fix store not started; pass :fixes (#{Exception.message(e)})"}
    catch
      :exit, _reason ->
        {:error, "code fix store not started; pass :fixes"}
    end
  end

  # ── Runner ─────────────────────────────────────────────────────────────

  defp run(runner, cmd, opts) do
    case runner.(cmd, opts) do
      {:ok, stdout} -> {:ok, stdout_to_string(stdout)}
      {:error, reason} -> {:error, format_reason(reason)}
      other -> {:error, "runner returned #{inspect(other)}"}
    end
  end

  defp stdout_to_string(out) when is_binary(out), do: out
  defp stdout_to_string(out), do: to_string(out)

  defp format_reason(reason) when is_binary(reason), do: reason
  defp format_reason(reason), do: inspect(reason)

  defp default_run(["git" | args], opts) do
    cd = Keyword.get(opts, :cd)
    git_opts = [stderr_to_stdout: true] ++ if(cd, do: [cd: cd], else: [])

    case OptimalSystemAgent.Git.cmd(args, git_opts) do
      {out, 0} -> {:ok, out}
      {out, _} -> {:error, String.trim(out)}
    end
  rescue
    e -> {:error, Exception.message(e)}
  end

  defp default_run([cmd | args], opts) when is_binary(cmd) do
    cd = Keyword.get(opts, :cd)
    sys_opts = [stderr_to_stdout: true] ++ if(cd, do: [cd: cd], else: [])

    case System.cmd(cmd, args, sys_opts) do
      {out, 0} -> {:ok, out}
      {out, _} -> {:error, String.trim(out)}
    end
  rescue
    e -> {:error, Exception.message(e)}
  end

  # ── Parse ──────────────────────────────────────────────────────────────

  defp parse_pr_url(stdout) when is_binary(stdout) do
    case Regex.run(~r{https://github\.com/\S+/pull/\d+}, stdout) do
      [url] -> String.trim_trailing(url, ".")
      _ -> nil
    end
  end

  defp resolve_sha(runner, run_opts, commit_out) do
    case run(runner, ["git", "rev-parse", "HEAD"], run_opts) do
      {:ok, out} -> parse_sha(out) || parse_sha(commit_out)
      {:error, _} -> parse_sha(commit_out)
    end
  end

  defp parse_sha(nil), do: nil

  defp parse_sha(stdout) when is_binary(stdout) do
    trimmed = String.trim(stdout)

    cond do
      Regex.match?(~r/\A[0-9a-f]{7,40}\z/i, trimmed) ->
        trimmed

      match = Regex.run(~r/\[(?:[^\]]+?) ([0-9a-f]{7,40})\]/i, stdout) ->
        List.last(match)

      true ->
        nil
    end
  end

  # ── Helpers ────────────────────────────────────────────────────────────

  defp default_branch(session_id) do
    "osa/autofix-" <> sanitize_session(session_id)
  end

  defp sanitize_session(session_id) do
    session_id
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9._-]+/, "-")
    |> String.trim("-")
    |> case do
      "" -> "session"
      s -> String.slice(s, 0, 80)
    end
  end

  defp field(map, key) when is_map(map) and is_atom(key) do
    Map.get(map, key) || Map.get(map, Atom.to_string(key))
  end

  defp diff_lines(text, prefix) do
    text
    |> String.split("\n")
    |> Enum.map(&(prefix <> &1))
    |> Enum.join("\n")
  end

  defp maybe_append_extra(parts, ""), do: parts
  defp maybe_append_extra(parts, extra), do: parts ++ [extra <> "\n"]
end
