defmodule OptimalSystemAgent.Auth.Providers.OpenAICodex do
  @moduledoc """
  Sign in with a ChatGPT Plus/Pro plan, so inference bills to the user's
  existing subscription instead of per-token API credit.

  ## The client id is borrowed. Read this before changing anything here.

  `app_EMoamEEZ73f0CkXaXp7hrann` is **OpenAI's Codex CLI's own OAuth client
  id**. OSA is not registered with OpenAI and there is **no public
  registration path** for one — this is not an oversight, no such path exists
  to apply through. Every third-party tool that offers ChatGPT-plan sign-in
  uses this same id; opencode ships the identical string.

  The position, recorded so a future maintainer does not mistake this for a
  sanctioned integration:

    * **Status: tolerated, not licensed.** OpenAI has publicly said it is
      working with other clients in this space, and there is no enforcement
      today. There is also no term, policy page, or written grant permitting
      it. Those are different things.
    * **Revocation is a live risk.** A borrowed id is a shared identity that
      OpenAI can invalidate at any time, without notice, for everyone at once.
      Treat a sudden `invalid_client` across all users as "this was turned
      off", not as a bug to debug.
    * **It was adopted knowingly**, as an explicit product decision, not by
      drifting into it.
    * **Unlike the Anthropic path OSA removed**, this is not a documented
      terms violation and is not blocked server-side. That is the entire
      distinction, and it is the reason one was deleted and this one exists.
      If OpenAI states a position against it, this module should follow
      `Auth.LegacyAnthropicOAuth` — removed, with an honest explanation.

  ## `originator`, and why OSA does not claim to be the Codex CLI

  OpenAI fronts `chatgpt.com/backend-api/codex` with a gate that prefers
  known first-party originators (`codex_cli_rs`, `codex_vscode`,
  `codex_sdk_ts`). The tool this was modelled on pins `originator:
  codex_cli_rs` — it claims to *be* the Codex CLI.

  OSA sends `osa` (override with `OSA_CODEX_ORIGINATOR`). Borrowing a client
  id because no alternative exists is a different act from actively asserting
  a false identity on every request, and only the second one is a lie the
  server could not otherwise make.

  **The known cost:** an honest originator may be 403'd, particularly from
  datacentre/VPS IPs. That failure is reported as
  `:originator_rejected` with a message that explains the trade-off, rather
  than being silently papered over by impersonation. If it proves
  unworkable in practice that is a decision for the operator to make
  explicitly via the env var — not a default OSA ships.

  ## Flow shape

  OpenAI's device flow is **not** RFC 8628, so `Auth.DeviceFlow` is not
  reused for the handshake (only its error classification is):

    1. `POST {issuer}/api/accounts/deviceauth/usercode` → `user_code` +
       `device_auth_id`
    2. user opens `{issuer}/codex/device` and types the code
    3. poll `POST {issuer}/api/accounts/deviceauth/token` — **403/404 mean
       "not yet"**, not failure, which is the single easiest thing to get
       wrong here
    4. the poll returns an `authorization_code` **and a server-supplied
       `code_verifier`**, exchanged at `/oauth/token`

  Because the verifier is issued by the server rather than generated by the
  client, this is PKCE in shape only; there is no client-side secret to
  protect beyond not logging it.
  """

  @behaviour OptimalSystemAgent.Auth.Subscription

  require Logger

  alias OptimalSystemAgent.Auth.DeviceFlow
  alias OptimalSystemAgent.Auth.SubscriptionStore
  alias OptimalSystemAgent.Utils.Browser

  @provider_id "openai_codex"
  @display_name "ChatGPT (Codex)"

  # See the moduledoc. Borrowed from OpenAI's Codex CLI; no public
  # registration exists. Do not change without reading that note.
  @client_id "app_EMoamEEZ73f0CkXaXp7hrann"

  @default_issuer "https://auth.openai.com"
  @default_base_url "https://chatgpt.com/backend-api/codex"

  @poll_min_interval_s 3
  @max_wait_s 900
  @refresh_skew_s 300
  # Login-request throttling is on OpenAI's side and is not a credential
  # problem; back off rather than failing the user's sign-in.
  @rate_limit_attempts 4

  @spec provider_id() :: String.t()
  def provider_id, do: @provider_id

  @spec display_name() :: String.t()
  def display_name, do: @display_name

  @doc "The base URL pinned into every credential written by this module."
  @spec default_base_url() :: String.t()
  def default_base_url,
    do: Application.get_env(:optimal_system_agent, :codex_base_url, @default_base_url)

  @doc """
  The `originator` OSA declares to OpenAI. Honest by default — see the
  moduledoc for why, and for what it can cost.
  """
  @spec originator() :: String.t()
  def originator do
    case System.get_env("OSA_CODEX_ORIGINATOR") do
      v when is_binary(v) and v != "" -> v
      _ -> Application.get_env(:optimal_system_agent, :codex_originator, "osa")
    end
  end

  @doc "Always available: unlike Copilot, the client id is compiled in."
  @spec available?() :: boolean()
  def available?, do: true

  defp issuer, do: Application.get_env(:optimal_system_agent, :codex_issuer, @default_issuer)
  defp client_id, do: Application.get_env(:optimal_system_agent, :codex_client_id, @client_id)

  defp req_options(extra) do
    Keyword.merge(
      [receive_timeout: 30_000, retry: false] ++ extra,
      Application.get_env(:optimal_system_agent, :auth_req_options, [])
    )
  end

  # ── Sign-in ─────────────────────────────────────────────────────────────

  @impl true
  @spec login(keyword()) :: {:ok, map()} | {:error, term()}
  def login(opts \\ []) do
    io = Keyword.get(opts, :io, &IO.puts/1)
    on_tick = Keyword.get(opts, :on_tick, fn -> :continue end)

    with {:ok, %{user_code: user_code, device_auth_id: id, interval: interval}} <-
           request_user_code(),
         :ok <- announce(user_code, interval, opts),
         :ok <- present(user_code, io, opts),
         {:ok, %{"authorization_code" => code, "code_verifier" => verifier}} <-
           poll_for_code(id, user_code, interval, on_tick),
         {:ok, tokens} <- exchange(code, verifier),
         {:ok, entry} <- persist(tokens) do
      io.("")
      io.("  ✓ Connected to #{@display_name}#{plan_suffix(entry)}")
      {:ok, entry}
    end
  end

  defp request_user_code(attempt \\ 1) do
    url = "#{issuer()}/api/accounts/deviceauth/usercode"

    case Req.post(req_options(url: url, json: %{"client_id" => client_id()}, headers: headers())) do
      {:ok, %{status: 200, body: body}} when is_map(body) ->
        user_code = body["user_code"]
        device_auth_id = body["device_auth_id"]

        if is_binary(user_code) and user_code != "" and is_binary(device_auth_id) do
          {:ok,
           %{
             user_code: user_code,
             device_auth_id: device_auth_id,
             interval: max(as_int(body["interval"]) || 5, @poll_min_interval_s)
           }}
        else
          {:error, :device_code_incomplete}
        end

      {:ok, %{status: 429} = resp} when attempt < @rate_limit_attempts ->
        # Exponential backoff, preferring the server's own Retry-After.
        delay = retry_after(resp) || Integer.pow(2, attempt)
        Process.sleep(min(max(delay, 1), 60) * 1000)
        request_user_code(attempt + 1)

      {:ok, %{status: 429}} ->
        {:error, :login_rate_limited}

      # Device-code auth is an account/org security setting on the ChatGPT
      # side, and it is off by default for some accounts. When it is off this
      # endpoint refuses before any code is ever issued, and the reason is in
      # the body — which this clause used to discard, leaving the user with a
      # bare status number and no way to know that a checkbox in someone
      # else's settings page was the whole problem.
      #
      # Surface the server's own words. Note the verification page OpenAI
      # serves says "…then run `codex login --device-auth` again", naming
      # their CLI; that instruction is wrong here and is deliberately not
      # repeated. The setting is the actionable half, and it is the same
      # setting whichever tool asks for the code.
      {:ok, %{status: status, body: body}} ->
        {:error, {:device_auth_refused, status, server_reason(body)}}

      {:error, e} ->
        {:error, {:transport_error, Exception.message(e)}}
    end
  rescue
    e -> {:error, {:transport_error, Exception.message(e)}}
  end

  # Pull a human-readable reason out of whatever shape the endpoint returned.
  # Nested `error.message` first (the documented shape), then the flat
  # variants, then a short raw string. Returns nil rather than inventing a
  # reason, so the caller can fall back to naming the status alone.
  defp server_reason(body) when is_map(body) do
    candidates = [
      get_in(body, ["error", "message"]),
      body["error_description"],
      body["message"],
      body["detail"],
      if(is_binary(body["error"]), do: body["error"])
    ]

    Enum.find_value(candidates, fn
      s when is_binary(s) -> if String.trim(s) != "", do: String.trim(s)
      _ -> nil
    end)
  end

  defp server_reason(body) when is_binary(body) do
    trimmed = String.trim(body)

    # A refusal page can come back as HTML; a wall of markup helps nobody.
    cond do
      trimmed == "" -> nil
      String.starts_with?(trimmed, "<") -> nil
      String.length(trimmed) > 300 -> String.slice(trimmed, 0, 300) <> "…"
      true -> trimmed
    end
  end

  defp server_reason(_), do: nil

  @doc """
  The verification URL the user must open. Public so a non-terminal surface
  can render it without reconstructing OpenAI's URL shape itself.
  """
  @spec verification_uri() :: String.t()
  def verification_uri, do: "#{issuer()}/codex/device"

  # Hand the code and URL to a structured consumer BEFORE the poll begins.
  #
  # `io` is a line printer, which is the right shape for a terminal and the
  # wrong shape for everything else: the TUI has to draw the code in a panel,
  # and a gateway whose stdout is a JSON-RPC pipe cannot print at all. Without
  # this callback the only way to learn the user code was to scrape it out of
  # a formatted English sentence, which is why the flow was reachable from
  # `osa setup` and from nowhere else.
  #
  # It fires before `present/3` so a caller that supplies both gets the
  # structured copy first, and a caller that supplies neither is unchanged.
  defp announce(user_code, interval, opts) do
    case Keyword.get(opts, :on_verification) do
      fun when is_function(fun, 1) ->
        fun.(%{
          user_code: user_code,
          verification_uri: verification_uri(),
          # OpenAI's device endpoint has no `verification_uri_complete`: the
          # code is typed, not embedded. Reported as nil rather than as a
          # fabricated URL with the code appended, which would 404.
          verification_uri_complete: nil,
          interval: interval,
          expires_in: @max_wait_s
        })

        :ok

      _ ->
        :ok
    end
  rescue
    # A rendering callback must never be able to fail a sign-in.
    _ -> :ok
  end

  defp present(user_code, io, opts) do
    url = "#{issuer()}/codex/device"

    io.("")
    io.("  To connect your ChatGPT plan:")
    io.("")
    io.("    1. Open  #{url}")
    io.("    2. Enter code  #{user_code}")
    io.("")
    io.("  You are connecting a ChatGPT account to OSA, a third-party tool.")
    io.("  Waiting for approval… (Ctrl-C to cancel)")

    if Keyword.get(opts, :open_browser, true), do: Browser.open(url)
    :ok
  end

  defp poll_for_code(device_auth_id, user_code, interval, on_tick) do
    deadline = System.monotonic_time(:second) + @max_wait_s
    do_poll(device_auth_id, user_code, interval, on_tick, deadline, 0)
  end

  defp do_poll(device_auth_id, user_code, interval, on_tick, deadline, transport_errors) do
    cond do
      System.monotonic_time(:second) >= deadline ->
        {:error, :device_code_timeout}

      on_tick.() == :cancel ->
        {:error, :cancelled}

      true ->
        Process.sleep(interval * 1000)

        options =
          req_options(
            url: "#{issuer()}/api/accounts/deviceauth/token",
            json: %{"device_auth_id" => device_auth_id, "user_code" => user_code},
            headers: headers()
          )

        case Req.post(options) do
          {:ok, %{status: 200, body: %{"authorization_code" => _} = body}} ->
            {:ok, body}

          # 403/404 mean "the user has not finished yet" — NOT an error.
          # Treating these as failures is the classic way to break this flow
          # entirely, since they are what the endpoint returns for most of the
          # sign-in's duration.
          {:ok, %{status: status}} when status in [403, 404] ->
            do_poll(device_auth_id, user_code, interval, on_tick, deadline, 0)

          {:ok, %{status: 200}} ->
            {:error, :device_code_incomplete}

          {:ok, %{status: status}} ->
            {:error, {:http_error, status}}

          # Transient by assumption, bounded by count. The user has already
          # approved this grant in their browser; throwing it away over one
          # dropped packet and demanding a fresh code is the most avoidable
          # failure in the flow. See `DeviceFlow`'s equivalent, which this
          # deliberately mirrors.
          {:error, e} ->
            reason = {:transport_error, Exception.message(e)}

            if transport_errors + 1 >= DeviceFlow.max_consecutive_transport_errors() do
              {:error, reason}
            else
              do_poll(device_auth_id, user_code, interval, on_tick, deadline, transport_errors + 1)
            end
        end
    end
  end

  defp exchange(code, verifier) do
    form = %{
      "grant_type" => "authorization_code",
      "code" => code,
      "redirect_uri" => "#{issuer()}/deviceauth/callback",
      "client_id" => client_id(),
      "code_verifier" => verifier
    }

    case Req.post(req_options(url: token_url(), form: form, headers: headers())) do
      {:ok, %{status: 200, body: %{"access_token" => _} = body}} -> {:ok, body}
      {:ok, %{status: 429}} -> {:error, :login_rate_limited}
      {:ok, %{status: _, body: %{"error" => e} = b}} -> {:error, DeviceFlow.classify(e, b)}
      {:ok, %{status: status}} -> {:error, {:http_error, status}}
      {:error, e} -> {:error, {:transport_error, Exception.message(e)}}
    end
  rescue
    e -> {:error, {:transport_error, Exception.message(e)}}
  end

  defp token_url, do: "#{issuer()}/oauth/token"

  # Only the user agent. Content-Type is deliberately NOT pinned here: the
  # deviceauth endpoints take JSON but the token exchange takes
  # x-www-form-urlencoded, and Req sets the correct header from whichever body
  # option is used. Hardcoding one of them mislabels the other — a
  # form-encoded body announced as JSON is rejected as malformed, which
  # presents as an opaque sign-in failure at the very last step.
  defp headers do
    [{"user-agent", DeviceFlow.user_agent()}]
  end

  # ── Persistence ─────────────────────────────────────────────────────────

  defp persist(tokens) do
    now = System.system_time(:second)
    access = tokens["access_token"]
    claims = jwt_claims(access)

    entry = %{
      "kind" => "device_code",
      "access_token" => access,
      "refresh_token" => tokens["refresh_token"],
      "id_token" => tokens["id_token"],
      "expires_at" => expires_at(tokens["expires_in"], now),
      "account_id" => claims["chatgpt_account_id"],
      "plan_type" => claims["chatgpt_plan_type"],
      # Pinned at sign-in so a `*_URL` override from an untrusted workspace
      # can never redirect a subscription bearer token to another host.
      "base_url" => default_base_url(),
      "connected_at" => now,
      "issued_by" => DeviceFlow.user_agent()
    }

    case SubscriptionStore.put(@provider_id, entry) do
      :ok -> {:ok, entry}
      err -> err
    end
  end

  defp expires_at(n, now) when is_integer(n) and n > 0, do: now + n

  defp expires_at(n, now) when is_binary(n) do
    case Integer.parse(n) do
      {v, _} when v > 0 -> now + v
      _ -> nil
    end
  end

  defp expires_at(_, _), do: nil

  @doc """
  Read the OpenAI auth claims out of an access token.

  The JWT is **not** verified: it is OSA's own credential, read only to
  display the plan and to populate the `ChatGPT-Account-ID` header. Nothing
  is authorised on the basis of these claims, so signature verification would
  add no security — and treating a malformed token as simply "no claims" is
  what keeps a cosmetic field from breaking a working sign-in.
  """
  @spec jwt_claims(String.t() | nil) :: map()
  def jwt_claims(token) when is_binary(token) do
    with [_h, payload | _] <- String.split(token, "."),
         {:ok, json} <- Base.url_decode64(payload, padding: false),
         {:ok, claims} when is_map(claims) <- Jason.decode(json) do
      Map.get(claims, "https://api.openai.com/auth", %{})
    else
      _ -> %{}
    end
  rescue
    _ -> %{}
  end

  def jwt_claims(_), do: %{}

  defp plan_suffix(%{"plan_type" => p}) when is_binary(p) and p != "", do: " (#{p} plan)"
  defp plan_suffix(_), do: ""

  # ── Status (pure read) ──────────────────────────────────────────────────

  @impl true
  def status do
    case SubscriptionStore.fetch(@provider_id) do
      nil ->
        OptimalSystemAgent.Auth.Subscription.disconnected(@provider_id)

      entry ->
        %{
          connected?: true,
          # A token OSA holds and can refresh is direct evidence.
          verified?: true,
          provider: @provider_id,
          account: entry["account_id"],
          plan: entry["plan_type"],
          expires_at: entry["expires_at"],
          expired?: expired?(entry)
        }
    end
  end

  @spec expired?(map()) :: boolean()
  def expired?(%{"expires_at" => at}) when is_integer(at), do: System.system_time(:second) >= at
  def expired?(_), do: false

  @spec needs_refresh?(map()) :: boolean()
  def needs_refresh?(%{"refresh_token" => rt} = entry) when is_binary(rt) and rt != "" do
    case entry["expires_at"] do
      at when is_integer(at) -> System.system_time(:second) >= at - @refresh_skew_s
      _ -> false
    end
  end

  def needs_refresh?(_), do: false

  # ── Token resolution ────────────────────────────────────────────────────

  @impl true
  def access_token do
    case SubscriptionStore.fetch(@provider_id) do
      nil ->
        {:error, :not_connected}

      entry ->
        cond do
          needs_refresh?(entry) -> refresh_and_get()
          expired?(entry) -> {:error, :refresh_token_invalid}
          true -> {:ok, entry["access_token"]}
        end
    end
  end

  @doc """
  The full credential needed to make a request: token, account id and base
  URL together.

  Returned as one value so call sites never have to re-read the store three
  times and risk seeing two different generations of the credential across
  a refresh.
  """
  @spec credential() :: {:ok, map()} | {:error, term()}
  def credential do
    with {:ok, token} <- access_token() do
      entry = SubscriptionStore.fetch(@provider_id) || %{}

      {:ok,
       %{
         access_token: token,
         account_id: entry["account_id"],
         plan_type: entry["plan_type"],
         base_url: entry["base_url"] || default_base_url()
       }}
    end
  end

  @doc """
  Refresh **because a request came back 401**, not because the clock said so.

  Proactive refresh alone is not enough, and the gap is not theoretical. All
  three of these produce a valid-looking token that the server rejects:

    * clock skew larger than the 5-minute window — nothing in OSA corrects for
      it, and `expires_at` is necessarily a wall-clock instant;
    * revocation from the provider's own UI between the skew check and the
      request;
    * any token whose `expires_at` is absent, which makes `expired?/1` and
      `needs_refresh?/1` permanently false — a dead credential with no exit.

  The argument is the token that was rejected, and it is what makes this safe
  to call concurrently. The predicate is "is the stored token still the one
  that just failed?" — so if a peer process already rotated it while this
  request was in flight, the fresh token is **adopted without a network call**
  and the rotating refresh token is never double-spent. That is the same
  single-spend guarantee `refresh_within_lock/3` gives the proactive path,
  expressed for a trigger that is a response rather than a deadline.
  """
  @spec force_refresh(String.t()) :: {:ok, String.t()} | {:error, term()}
  def force_refresh(rejected_token) when is_binary(rejected_token) do
    refresh_and_get(fn entry -> entry["access_token"] == rejected_token end)
  end

  defp refresh_and_get(needs_refresh? \\ &needs_refresh?/1) do
    result =
      SubscriptionStore.refresh_within_lock(
        @provider_id,
        fn entry ->
          form = %{
            "grant_type" => "refresh_token",
            "refresh_token" => entry["refresh_token"],
            "client_id" => client_id()
          }

          case Req.post(req_options(url: token_url(), form: form, headers: headers())) do
            {:ok, %{status: 200, body: %{"access_token" => access} = body}} ->
              now = System.system_time(:second)
              claims = jwt_claims(access)

              {:ok,
               entry
               |> Map.put("access_token", access)
               |> Map.put("refresh_token", body["refresh_token"] || entry["refresh_token"])
               |> Map.put("id_token", body["id_token"] || entry["id_token"])
               |> Map.put("expires_at", expires_at(body["expires_in"], now))
               |> Map.put("account_id", claims["chatgpt_account_id"] || entry["account_id"])
               |> Map.put("plan_type", claims["chatgpt_plan_type"] || entry["plan_type"])
               |> Map.put("last_refresh", now)}

            {:ok, %{status: status, body: %{"error" => e} = b}} when status in [400, 401] ->
              {:error, DeviceFlow.classify(e, b)}

            {:ok, %{status: status}} ->
              {:error, {:http_error, status}}

            {:error, e} ->
              {:error, {:transport_error, Exception.message(e)}}
          end
        end,
        needs_refresh?
      )

    case result do
      {:ok, entry} ->
        clear_refresh_failures()
        {:ok, entry["access_token"]}

      {:error, :refresh_token_invalid} = err ->
        # Deleting a credential is destructive and irreversible from the
        # user's side — they have to run the whole sign-in again — so it takes
        # TWO consecutive rejections, not one. Providers do return
        # `invalid_grant` for transient reasons, and a single bad minute
        # signing someone out mid-conversation is a worse outcome than one
        # extra failed turn. `refresh_token_reused` is not in this branch and
        # never should be: reuse detection is definitive and is handled as a
        # terminal error immediately.
        if record_refresh_failure() >= 2 do
          Logger.warning(
            "[Auth] #{@display_name} rejected the refresh token twice in a row; signing out locally."
          )

          _ = SubscriptionStore.delete(@provider_id)
          clear_refresh_failures()
          err
        else
          Logger.warning(
            "[Auth] #{@display_name} rejected a token refresh. Keeping the credential — " <>
              "a second consecutive rejection will sign you out."
          )

          err
        end

      err ->
        err
    end
  end

  # Consecutive `invalid_grant` count, in `:persistent_term` because it must
  # survive across turns within an OS process but is worthless across a
  # restart — a fresh process re-testing the credential once is exactly the
  # right behaviour.
  defp record_refresh_failure do
    n = :persistent_term.get({__MODULE__, :refresh_failures}, 0) + 1
    :persistent_term.put({__MODULE__, :refresh_failures}, n)
    n
  end

  defp clear_refresh_failures, do: reset_refresh_failures()

  @doc """
  Forget the consecutive-refresh-failure count.

  Public so a test can establish a known starting point — the counter is
  process-global by design (it must survive across turns) and would otherwise
  leak between tests, which is a good way to make a two-strike rule look like
  a one-strike rule intermittently.
  """
  @spec reset_refresh_failures() :: :ok
  def reset_refresh_failures do
    :persistent_term.put({__MODULE__, :refresh_failures}, 0)
    :ok
  end

  @impl true
  def logout, do: SubscriptionStore.delete(@provider_id)

  # ── helpers ─────────────────────────────────────────────────────────────

  defp retry_after(%{headers: headers}) when is_map(headers) do
    headers |> Map.get("retry-after", []) |> List.wrap() |> List.first() |> as_int()
  end

  defp retry_after(_), do: nil

  defp as_int(v) when is_integer(v), do: v

  defp as_int(v) when is_binary(v) do
    case Integer.parse(v) do
      {n, _} -> n
      _ -> nil
    end
  end

  defp as_int(_), do: nil
end
